services:

  zz-traefik:
    container_name: zz-traefik
    build:
      context: ./zz-traefik
      args:
        ACME_EMAIL: ${ACME_EMAIL}
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  zz-httpbin:
    container_name: zz-httpbin
    build: 
      context: .
      dockerfile: zz-Dockerfile
    restart: unless-stopped
    ports:
      - "8080:80"
    labels:
      - "traefik.enable=true"
      - traefik.http.services.zz-httpbin.loadbalancer.server.port=80

      # Middleware для удаления заголовка Server
      - traefik.http.middlewares.zz-remove-server-headers.headers.customResponseHeaders.Server=

      # Middleware для компрессии
      - traefik.http.middlewares.zz-compress.compress=true
      
      # HTTP
      - traefik.http.routers.zz-http.rule=Host(`${DOMAIN:-localhost}`)
      - traefik.http.routers.zz-http.entrypoints=web
      - traefik.http.routers.zz-http.middlewares=SslHeader@file,zz-compress,zz-remove-server-headers

      # HTTPS
      - traefik.http.routers.zz-https.rule=Host(`${DOMAIN:-localhost}`)
      - traefik.http.routers.zz-https.entrypoints=websecure
      - traefik.http.routers.zz-https.middlewares=SslHeader@file,zz-compress,zz-remove-server-headers
      - traefik.http.routers.zz-https.tls=true
      - traefik.http.routers.zz-https.tls.certresolver=${CERT_RESOLVER:-letsencrypt}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/get"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 10s